<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>NttBank.QueryAgent.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OllamaSharp"/>
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Asp.Versioning.Http"/>
    <PackageReference Include="FluentValidation"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent\Agent.csproj"/>
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj"/>
  </ItemGroup>

</Project>
